### ISSUE TITLE
p5.Vector suggestion snippet creates new P5.Vector

### ISSUE THREAD

**Issue by Hifilo** [Dmkk01/p5-dev-tools#3]
Hello, Thanks for making this extension. I came across a minor issue while working with it.

Anytime I use the p5.vector suggestion in vscode the autocomplete fills out `new p5.Vector()` which I don't want.

can I comment this out locally, so it doesn't get in the way? or am I not using it correctly?

https://github.com/Dmkk01/p5-dev-tools/assets/92943726/52007da1-4a6a-4e35-92ea-da42d30975f8

**Comment by Dmkk01** [comment]
Hey, thanks for bringing out the issue. 

I have also encountered this problem myself, but I was not sure what to do with it, but I have just added a new version with the updated `p5.Vector` autocompletion.

Currently there will be two commands for creating the vectors: 
`p5.VectorNew` -> `new p5.Vector(x, y, z)`

`p5.Vector` -> `p5.Vector`

**Comment by Hifilo** [comment]
Awesome, it's running smoothly now. Thanks!

**Comment by Hifilo** [comment]
I thought Id post this here, since I don't think it needs another issue thread, but in the main snippets file I noticed that p5 circle & p5 square both share the prefix p5-circle.

**Comment by Dmkk01** [comment]
Oh, great catch, I will fix that right away as well
